name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
  schedule:
    # Run security scan daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  DOCKERHUB_IMAGE: sirantd/aws-helm-kubectl
  GHCR_IMAGE: ghcr.io/perun-engineering/aws-helm-kubectl

jobs:
  define:
    runs-on: ubuntu-latest
    outputs:
      kubernetes_versions: ${{ steps.read_env.outputs.versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - name: Read environment file
        id: read_env
        run: |
          # Extract only the KUBERNETES_VERSIONS line and get the array part
          VERSIONS=$(grep '^KUBERNETES_VERSIONS=' .env | cut -d'=' -f2-)
          echo "versions=$VERSIONS" >> $GITHUB_OUTPUT
          echo "Testing with Kubernetes versions: $VERSIONS"

  security-scan:
    needs: define
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{fromJson(needs.define.outputs.kubernetes_versions)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Read environment file
        run: |
          cat .env >> ${GITHUB_ENV}
          echo "=== Environment variables ==="
          cat .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ${{ env.DOCKERHUB_IMAGE }}:${{ matrix.version }}-test
          build-args: |
            KUBE_VERSION=${{ matrix.version }}
            HELM_VERSION=${{ env.HELM_VERSION }}
            SOPS_VERSION=${{ env.SOPS_VERSION }}
            HELM_SECRETS_VERSION=${{ env.HELM_SECRETS_VERSION }}
            HELM_S3_VERSION=${{ env.HELM_S3_VERSION }}
            HELMFILE_VERSION=${{ env.HELMFILE_VERSION }}
            AWS_CLI_VERSION=${{ env.AWS_CLI_VERSION }}
            HELM_DIFF_VERSION=${{ env.HELM_DIFF_VERSION }}
            ALPINE_PYTHON=${{ env.ALPINE_PYTHON }}
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}

      - name: Run Trivy vulnerability scanner (SARIF report)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKERHUB_IMAGE }}:${{ matrix.version }}-test
          format: 'sarif'
          output: 'trivy-results-${{ matrix.version }}.sarif'
          severity: 'CRITICAL,HIGH'  # Report all for visibility, but don't fail

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results-${{ matrix.version }}.sarif'

      - name: Run Trivy vulnerability scanner (informational only)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKERHUB_IMAGE }}:${{ matrix.version }}-test
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Test image functionality
        run: |
          echo "Testing image functionality..."
          docker run --rm ${{ env.DOCKERHUB_IMAGE }}:${{ matrix.version }}-test /bin/bash -c "
            echo 'Testing tool versions:' &&
            kubectl version --client &&
            helm version &&
            aws --version &&
            sops --version &&
            helmfile --version &&
            echo 'All tools working correctly!'
          "
